server:
  port: 8081
spring:
  application:
    name: feign-consume
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:12346/eureka/


feign:
  hystrix:
    enabled: true

hystrix:
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 50000 #hystrix超时熔断时间

ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
    ConnectTimeout: 1000 #请求连接超时时间
    ReadTimeout: 10000 #请求处理的超时时间
    OkToRetryOnAllOperations: true #对所有请求都进行重试 false：所有get重试，true：get，post都会重试
    MaxAutoRetriesNextServer: 1 #切换实例的重试次数,不包括首次调用
    MaxAutoRetries: 2 #同一台实例最大重试次数,不包括首次调用






